version: '2.1'
services:
      dependensee:
        image: percussiveelbow/dependensee
        command: bash -c "rails db:create db:migrate RAILS_ENV=production && rails server -e production -p 3000 -b '0.0.0.0'"
        ports:
          - "3000:3000"
        depends_on:
            postgres:
              condition: service_healthy
        links:
          - postgres
        volumes:
        - tmp:/tmp
        healthcheck:
          test: ["CMD-SHELL","curl http://localhost:3000 || exit 1"] 
          interval: 60s
          timeout: 60s
          retries: 3
        environment:
          SECRET_KEY_BASE: ${RAILS_SECRET}
      postgres:
        image: postgres:9.4
        ports:
          - "5432"
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 3s
          timeout: 30s
          retries: 3
      dependensee-ui:
        image: percussiveelbow/dependensee-ui
        ports:
          - "80:80"
volumes:
  tmp: