source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'git'
gem 'nokogiri'
gem 'prawn'
gem 'rubyzip'
gem 'simplecov'
gem 'sinatra'
gem 'test-unit-full'